name: Get more
on:
  push:
    paths:
    - './extra_link'
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest  
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Collect
      run: |
        sudo apt-get install -y wget
        mkdir -p link
        mkdir -p release
        bash extra.sh

    - name: Read tag name
      id: read_tag_name
      uses: andstor/file-reader-action@v1
      with:
        path: "release_tag.txt"

    - name: Echo tag name
      run: echo "Uploading more files for release ${{ steps.read_tag_name.outputs.contents }}"

    - name: Commit
      uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'extra_link'
        # tag: ${{ steps.read_tag_name.outputs.contents }}

    
    - name: Publish archives and packages
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.read_tag_name.outputs.contents }}
      #  body: "This is a test"
      #  draft: true
      #  prerelease: true
        files: release/*
      #env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
