name: Collect
on:
  workflow_dispatch:
  schedule:
    #Run at 12am every Sunday
    - cron: "0 0 * * 0"

jobs:
  collect:
    runs-on: ubuntu-latest  
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Collect
      run: |
        sudo apt-get install -y wget
        mkdir -p link
        mkdir -p release
        bash collect.sh

    - name: Check file existence
      id: check_release
      uses: andstor/file-existence-action@v1
      with:
        files: "release_tag.txt"

    - name: Read tag
      if: steps.check_release.outputs.files_exists == 'true'
      id: read_tag
      uses: andstor/file-reader-action@v1
      with:
        path: "release_tag.txt"

    - name: Show tag
      if: steps.check_release.outputs.files_exists == 'true'
      run: echo "Creating release ${{ steps.read_tag.outputs.contents }}"

    - uses: mukunku/tag-exists-action@v1.6.0
      if: steps.check_release.outputs.files_exists == 'true'
      id: git_tag_check
      with:
      #  github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: '${{ steps.read_tag.outputs.contents }}'

    - name: Show existing tag
      if: steps.git_tag_check.outputs.exists == 'true'
      run: echo "${{ steps.read_tag.outputs.contents }}"

    - name: Commit and tag
      if: steps.git_tag_check.outputs.exists == 'false' 
      uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'link'
        tag: ${{ steps.read_tag.outputs.contents }}

    - name: Commit but don't tag
      if: steps.git_tag_check.outputs.exists == 'true' 
      uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'link'

    - name: Read link file
      if: steps.check_release.outputs.files_exists == 'true'
      id: read_link_file
      uses: andstor/file-reader-action@v1
      with:
        path: "release_link.txt"

    - name: Echo link file
      if: steps.check_release.outputs.files_exists == 'true'
      run: |
        if [ ${{ steps.read_link_file.outputs.contents }} == "Lost" ]; then
          echo "No package available for ${{ steps.read_tag.outputs.contents }}"
        fi

    - name: Publish archives and packages
      if: steps.check_release.outputs.files_exists == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.read_tag.outputs.contents }}
      #  body: "This is a test"
      #  draft: true
      #  prerelease: true
        files: release/*
      #env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
