name: Download nightly
on:
  schedule:
    - cron: "0 0 * * *"

  push:

jobs:
  collect:
    runs-on: ubuntu-latest  
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Collect
      run: |
        sudo apt-get install -y wget
        if [ ${{ secrets.INIT_TOKEN }} = 'yes' ]; then
          mkdir -p link
          mkdir -p release
          bash collect.sh
        else
          bash update.sh
        fi

#    - name: Update initialize flag
#      uses: msanjose/github-secret-updater@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        owner: ${{ github.repository_owner }}
#        repo: ${{ github.repository_name }}
#        secret-id: 'INIT_TOKEN'
#        secret-value: 'no'

    - name: Early exit
      run: |
        if [ ! -f release_tag.txt ]; then
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        fi
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Read file contents
      id: read_file
      uses: andstor/file-reader-action@v1
      with:
        path: "release_tag.txt"

    - name: File contents
      run: echo "Creating release ${{ steps.read_file.outputs.contents }}"

    - name: Commit
      uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'link'
        tag: ${{ steps.read_file.outputs.contents }}

    - name: Publish archives and packages
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.read_file.outputs.contents }}
      #  body: "This is a test"
      #  draft: true
      #  prerelease: true
        files: release/*
      #env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
